### ISSUE TITLE
ARM64 build

### ISSUE THREAD

**Issue by ymontmarin** [conda-forge/libusockets-feedstock#5]
Hi everyone,

Would it be possible to make this recipe build a package version for the ARM64 platform? Having tested it on an Apple M1 laptop, the `build.sh` should work as it is.

Thank you in advance.

ymm

**Comment by traversaro** [comment]
Fixed by https://github.com/conda-forge/libusockets-feedstock/pull/6, thanks @ymontmarin for opening the PR that triggered the bot!
